name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
    tags: ["*"]

jobs:
  test:
    name: Test with Node ${{ matrix.node-version }} & TypeScript ${{ matrix.typescript-version }}
    # concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "latest"
          - "~22"
          - "~20"
          - "~18"
          - "~16"
        typescript-version:
          - "latest"
          - "~5.4"
          - "~5.3"
          - "~5.2"
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node ğŸª¢
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install ğŸ”§
        run: |
          npm install
          npm install -D typescript@${{ matrix.typescript-version }}

      - name: Test âœ…
        run: npm run test
